/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ProfileGenerator {
  constructor(opts: ProfileGeneratorOptions)
  addSample(audio: Float32Array, phonemeName: string, inputSampleRate: number): void
  finish(): string
}

export declare const enum CompareMethod {
  L1Norm = 0,
  L2Norm = 1,
  CosineSimilarity = 2
}

export interface ProfileGeneratorOptions {
  targetSampleRate: number
  melFilterBankChannels: number
  compareMethod?: CompareMethod
  mfccDataCount?: number
  sampleCount?: number
  useStandardization?: boolean
}
